ryu-AIMS/HierarchicalRouting.jl

src/optimization/solution_assessment.jl

- Implement `Random.shuffle` to avoid while loops to resample `rand`
- Introduce `enforce_diff_sortie` arg as a flag to enforce selecting different sorties
- Clean up function: use aliases, typing, comment
- Update docstring
Closes #9

Optimize random sortie selection in perturb_swap_solution()

---

src/clustering/clustering.jl
src/problem/problem_setup.jl
src/processing/reads.jl

Apply 3d kmeans for *disturbance* clustering.
- Disturbance values (i.e., wave data at each point) used to create additional correlation between points
- Random number `k_d` clusters generated (within bounds) to vary the magnitude of disturbance
- Reverts clustering calcs to euclidean from haversine

Implement 3d clustering

---

src/HierarchicalRouting.jl
src/clustering/clustering.jl
src/problem/disturbance_events.jl
src/problem/solve_problem.jl
src/processing/reads.jl
src/routing/routing_heuristics.jl

Disturbances generated twice before 2nd and 4th clusters ('magic number' arbitrary locations for now).
Removes nodes that have been *clustered* for disturbances based on their disturbance scores. These nodes have been grouped by score, averaged within the group, and perturbed as a group by a random arithmetic operator. 
The group with the highest score is removed.
- Cluster ID consistency is ensured (before and after disturbances)
- Warnings are generated if too few locations remain based on required number of future deployment clusters to be visited
- `disturbed_cluster_sets` atrribute introduced to MSTSolution struct

Disturbances affect clustering of unvisited deployment locations

---

src/plotting/plots.jl

- Plots mothership route as *thicker* black line to distinguish from tender sorties
- Multiple dispatch for `tenders!()` to allow partially completed clusters to be plotted
- i.e., for plotting partial solutions at disturbance events
- Shades tender sorties sequentially within clusters

Updates plot visualisations for plotting partial (disturbed) solutions, and tender sortie shading

---

src/problem/problem_setup.jl
src/routing/feasible_paths.jl

Ensures that target points are not wrongly excluded by simplified exclusion polygons by inserting target points found within polygons as new vertices.
Closes #15, #29

Adjusts exclusions to prevent target exclusion

---

src/clustering/clustering.jl
src/problem/disturbance_events.jl
src/problem/problem_setup.jl
src/processing/processing.jl
src/processing/reads.jl
src/routing/feasible_paths.jl

- Connects all **visible** polygon vertices, rather than only **adjacent** vertices to avoid following crevices unnecessarily, when:
- final point is contained within a convex hull (and not visible), in `build_graph()`; and
- initial point is contained within a convex hull, in `shortest_feasible_path()`.
- Includes `else` statement in `build_graph()` to catch scenarios where `initial_point` and `final_point` are visible.
Closes #27

Corrects feasible routes around polygons to follow shortest feasible path

---

README.md
src/optimization/metric_calcs.jl
src/optimization/solution_assessment.jl
src/problem/solve_problem.jl

Refactors solution perturbation logic to improve optimization:
- Implements a boolean flag to consider inclusoin of cross-cluster swaps.
- If flag = true: Implements sub-cluster and cross-cluster node swaps with a 50/50 probability to diversify search.
- Introduces separate exclusion DataFrames for mothership and tenders for mothership route update during perturbation.
- Adds functionality to insert unallocated nodes into existing clusters and sorties to improve initial solutions.

Improves solution optimization with cross-cluster perturbation and node insertion

---

src/clustering/clustering.jl
src/problem/solve_problem.jl

Enhances clustering algorithm by introducing `capacitated_kmeans()` to adhere to capacity constraints by:
- clustering locations while ensuring no cluster exceeds a maximum size.
- splitting (creating an extra) clusters when distance to another available cluster is too large.
- Removes unnecessary parameters from `cluster_problem()`
- `num_clusters`: not relevant when clusters are capacity-constrained as over-capacity clusters are split.
- `cluster_tolerance`: un-used

Improves clustering with capacity constraints

---

README.md
src/clustering/clustering.jl
src/optimization/solution_assessment.jl
src/problem/solve_problem.jl

The previous approach hardcoded an RNG (Random Number Generator) and seed value into the package module itself.
```julia
Q = 1234
GLOBAL_RNG = MersenneTwister(Q)
```
This would have the opposite effect of reproducibility as it ensures completely different results on each run.
It would also be confusing to the user who sets a value for `Random.seed!()` because the global RNG is not used at all - so results would appear to change even if a consistent/identical seed value is used on repeat runs.
```julia
using Random
Random.seed!(101)
problem = load_problem(
"data/target_locations (scenarios)/output_slopes_3-10m.geojson",           # target_path
"data/target_cluster (site)/Moore_2024-02-14b_v060_rc1.gpkg",               # subset_path
"data/env_constraints/Cairns-Cooktown_bathy.tif", …
```

Remove hardcoded RNG

---

src/plot/plot.jl

Tentative implementation of a method that can produce a plot for assessment/analysis/publication.
```julia
import HeirarchicalRouting as HR
f, ax = HR.Plot.solution(problem, soln)
```
@ryu-AIMS could you flesh this out please?
Flagging also that I find the ergonomics of the current set of plotting methods uncomfortable (in my opinion of course).
Typically with methods that "plot" something, I'd expect the figure to appear but the current convention of returning both the figure and axis objects prevent this.
Don't worry about this right at this moment but I suggest refactoring the plotting module to only return the figure.
The axis can be retrieved using the Makie API if you need it, as mentioned in the Makie documentation:

Add initial convenience plotting method

---

src/plot/plot.jl

Closes #72 
Handles potential mismatch between length of tender ids and their actual id values.
e.g., there may be 5 tenders but their ids may be 1, 2, 100, 3, 8.
I suspect, however, that there is a deeper issue if tender IDs are being dropped?

Fix tender route plotting

---

README.md
src/plot/plot.jl
src/routing/routing_heuristics.jl

Updates plot module by 
renaming `linestrings()` to `route()` and 
adding multiple dispatch and docstrings for `route!()`
to improve clarity and consistency by adopting a more descriptive name.
Updates README documentation and examples to reflect the new naming scheme.
Closes #74

Renames plotting methods 

---

README.md
src/plot/plot.jl

- Refactors `clusters!()` and `tenders!()`
- Splits `clusters()` and `clusters!()` into multiple methods to handle different input types (clusters, cluster sequences).
- Refactors cluster data extraction for clarity and efficiency.
- Introduces `create_colormap()` to centralize colormap generation for tenders and clusters based on IDs.
- Uses maximum ID for color mapping, to ensure:
- mismatch does not occur, and 
- consistent colors of clusters and tenders across plots.
- Functions out `route!()` to improve code reuse within `tenders!()`.
- Improves cluster plotting with better centroid indexing and radius calculation.
- Corrects centroid type as `Point`s.
Closes #72

Refactors plot functions and ensure color matching for clusters and tenders

---

src/plot/plot.jl

Adds `clusters` and `cluster_sequence` as (required) positional rather than (optional) keyword arguments to ensure multiple dispatch on different types.
Updates docstrings to match

Corrects `clusters()` and `clusters!()` function signatures

---

src/problem/solve_problem.jl

- Sorts clusters by ID to ensure consistent behaviour and expected results.
- Corrects an indexing error in the cluster sequence to avoid out-of-bounds issues.
- Removing an unused counter variable.

Corrects cluster indexing in solution process

---

src/show.jl

Corrects `TenderSolution` show method, where wrongly copied variables/attributes were causing errors.
Adds a show method for `Vector{TenderSolution}` directly.

Fixes show method errors

---

src/plot/plot.jl

Simply reorders plotting order to avoid route lines overlapping text

Reorder layer order for figure clarity

---

src/plot/plot.jl

For `Plot.solution()` of two axes
- Adds cost annotation for each axis, including accurate vessel weightings.
- Corrects `exclusions!()` broadcast to use `Ref()`
- Defaults to show mothership exclusions

Fixes two-axis plot

---

src/processing/processing.jl
src/routing/routing_heuristics.jl

Rebuilds tender sorties after waypoint optimization by checking for changed start and/or sortie points (which are mothership waypoints). If these points have been perturbed, update linestrings in that segment of the tender sortie. Sorties/segments without changes do not need to be updated.
- Corrects tender sortie logic to ensure linestrings adhere to exclusion zone feasibility at each rebuild, rather than ignoring and then rebuilding at end.
- Avoiding unnecessary sortie rebuilds by checking if start/end points have moved
- Rebuilds only necessary segments of line strings, improving performance
- Functions out linestring segmentation and re-calcs in `generate_tender_sorties()` to:
- `rebuild_sortie()`
- `update_segment()`
- `linestring_segment_to_keep()`
- Refactors to improve logic
- …

Corrects and refactors tender sortie rebuild process

---

src/problem/problem_setup.jl
src/processing/data_types.jl
src/processing/reads.jl

Specifies a concrete vector type to store geometries as a `POLY_VEC` to avoid potential type instability issues.

Resolves errors with reading/processing cached files
